//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TresNight.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitchen
    {
        public int Id_User { get; set; }
        public int Products { get; set; }
        public int Pcs { get; set; }
        public System.DateTime Date_recorde { get; set; }
        public int Id_zone { get; set; }
        public int Id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
